Jenkins v1.28

diff --git a/charts/account-service/templates/tests/test-connection.yaml b/charts/account-service/templates/tests/test-connection.yaml
--- a/charts/account-service/templates/tests/test-connection.yaml
+++ b/charts/account-service/templates/tests/test-connection.yaml
@@ -1,15 +1,24 @@
 apiVersion: v1
 kind: Pod
 metadata:
-  name: "{{ include \"account-service.fullname\" . }}-test-connection"
-  labels:
-    {{- include \"account-service.labels\" . | nindent 4 }}
+  name: "bankapp-dev-account-service-test-connection"
   annotations:
     "helm.sh/hook": test
 spec:
   containers:
-    - name: wget
+    - name: account-service-test
       image: busybox
       command: ['sh', '-c']
-      args: ['wget -S --spider {{ include "account-service.fullname" . }}:{{ .Values.service.port }} || true']
+      args:
+        - |
+          response=$(wget -S --spider http://bankapp-dev-account-service:8081/ 2>&1 | grep "HTTP/" | tail -1)
+          echo "Response: $response"
+          # Проверяем, что ответ содержит 404 (или любой другой ожидаемый код)
+          if echo "$response" | grep -q "404\|200\|204"; then
+            echo "Test passed: received expected HTTP code"
+            exit 0
+          else
+            echo "Test failed: received unexpected HTTP code"
+            exit 1
+          fi
   restartPolicy: Never
